### ISSUE TITLE
This is interesting to me

### ISSUE THREAD

**Issue by voidfiles** [arlobelshee/AgileEngineeringFluency#9]
I've been looking at it as a way to help teams I work with move from where they are to where they want to be. But, many of the steps are missing descriptions and they don't all make sense to me.

What kind of help do you need to fill in the data?

**Comment by arlobelshee** [comment]
Awesome. I'm glad you are finding it a useful starting point.

I'm happy to accept PRs. I'd love to get at least some basic descriptions for each element.

You could also send me a PR with questions in any item that doesn't make sense to you. Or fill in key ideas for anything you want to help others get.
